30. added instructor dashboard. Added button to chrome extension to r…
JKChenFZ/Minerva pull request #57
Opened 2020-11-01 23:31 UTC by MrNickWan

…edirect to dashboard

![image](https://user-images.githubusercontent.com/22458861/97818424-687efe00-1c70-11eb-9a4e-d29739548104.png)

![image](https://user-images.githubusercontent.com/22458861/97818439-759bed00-1c70-11eb-9e39-ca5dc607b43b.png)

2020-11-02 12:08 UTC, MrNickWan commented
![image](https://user-images.githubusercontent.com/22458861/97866556-238fb180-1cda-11eb-9dca-daa035adc52f.png)

2020-11-02 18:42 UTC, JKChenFZ requested changes
Overall the mock UI looks fine.

Due to migration, please see #59 for integration and import updates
Due to change to active feed discussed previously, please make sure the mock UI supports the following.
1. Data points provided from active and passive feedback are both time points to frequencys (e.g. 123:5, there are 5 counts of feedback at time 123 seconds)
    1. However, it is best to reflect active feedback data points in a bar graph approach and the passive feedback data points the way you illustrated in the screenshot. The reason is that passive feedback takes realtime feedback and encapsulates a range of time.
2. For the active feedback data points, please make each bar (time point) clickable and render a modal which shows the actual textual questions at that point of time (You will be given the student names and the corresponding question text). You can leverage sweetAlert2 which is already part of project dependency.

2020-11-02 18:42 UTC, Jason-KChen commented on package-lock.json
> +{
Is this the legacy of your previous merge conflict resolution?

2020-11-02 18:42 UTC, Jason-KChen commented on extension/src/popups/MinervaMenu.html
> +            <li class="nav-item">
Having a button from the popup is fine. However, having it directly visible in the student interaction view is not so desirable

Suggestions:
1. Invisible trigger in the popup (e.g. monitor the "?" key press to trigger the handler function)
2. Add the button to the setting pages of the chrome extension ([source](https://developer.chrome.com/extensions/options#write_page))

2020-11-02 18:42 UTC, Jason-KChen commented on extension/src/InstructorDashboard/InstructorDashboard.js
> +
nit: remove

2020-11-02 18:42 UTC, Jason-KChen commented on extension/src/InstructorDashboard/InstructorDashboard.js
> +displayFormatFunction = function(label, index, labels) {
Let's stick to `function displayFormat(label, index, labels)` convention instead of var declaration

2020-11-02 18:42 UTC, Jason-KChen commented on extension/src/InstructorDashboard/InstructorDashboard.js
> +displayStudents = function (TooltipItem, object) {
same as above

2020-11-03 15:42 UTC, MrNickWan reviewed
> Overall the mock UI looks fine.
> 
> Due to migration, please see #59 for integration and import updates
> Due to change to active feed discussed previously, please make sure the mock UI supports the following.
> 
> 1. Data points provided from active and passive feedback are both time points to frequencys (e.g. 123:5, there are 5 counts of feedback at time 123 seconds)
>    
>    1. However, it is best to reflect active feedback data points in a bar graph approach and the passive feedback data points the way you illustrated in the screenshot. The reason is that passive feedback takes realtime feedback and encapsulates a range of time.
> 2. For the active feedback data points, please make each bar (time point) clickable and render a modal which shows the actual textual questions at that point of time (You will be given the student names and the corresponding question text). You can leverage sweetAlert2 which is already part of project dependency.

I'm confused as to how we would display active feedback as a bar graph. A bar graph implies we have distinct categories for each individual bar. But students are submitting their own individual questions. We would have as many bars as student questions. Or would each bar represent a separate video?

2020-11-03 15:42 UTC, r00t-admin commented on extension/src/popups/MinervaMenu.html
> +            <li class="nav-item">
1. I can't do this because we have no concept of student or teacher in the backend.
We have no login data for either. So the button being visible to students is a temporary measure.
2. I think implementing it this way is unnecessary because once we implement student and teacher login info, we'll just implement your first suggestion (which I think is the correct way). But again, we need teacher and student context into the chrome extension.

2020-11-03 15:42 UTC, r00t-admin commented on package-lock.json
> +{
I installed chart.js but I am using a CDN now.
Will remove this.

2020-11-03 18:03 UTC, JKChenFZ requested changes
>I'm confused as to how we would display active feedback as a bar graph. A bar graph implies we have distinct categories for each individual bar. But students are submitting their own individual questions. We would have as many bars as student questions. Or would each bar represent a separate video?

The way I envision active feedback is that, the graph is filled with individual bar where the x-axis is the discrete timestamp of a video and the y-axis is the occurrences of questions. Even though each student ask his or her own questions, we still want a way to link similar questions together. The way I would like to define similarity is through the corresponding timestamp. If `A` and `B` both ask a question at time `100` in the same video, the active feedback graph should have a bar of height `2` at timestamp `100`. By clicking on that bar in the graph, a modal should pop up illustrating the actual textual content.

```
A asked: ********
B asked: ***************
```

2020-11-03 18:03 UTC, Jason-KChen commented on extension/.eslintrc.json
> +        "Chart": false
If you install it correctly, this should not be here

2020-11-03 18:03 UTC, Jason-KChen commented on extension/dist/manifest.json
> +  "content_security_policy": "script-src 'self' 'sha256-t9UJPrESBeG2ojKTIcFLPGF7nHi2vEc7f5A2KpH/UBU=' 'sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z' 'sha384-B4gt1jrGC7Jh4Ag
Same as above. Keep the original content under `content_security_policy` untouched should be the route going foward

2020-11-03 18:03 UTC, Jason-KChen commented on extension/webpack.config.js
> +        InstructorDashboard: "./src/standalone_pages/InstructorDashboard.js",
This is fine, but please sort them with respect to alphabetical order

2020-11-03 18:03 UTC, Jason-KChen commented on extension/src/popups/MinervaMenu.html
> +            <li class="nav-item">
My first point was really just about hiding the button. I am ok with a temporary measure which exposes the button for demonstration purpose.

As with the second approach, ideally, we should separate and containerize the context with respect to students and teachers. However, at the current rate of implementation, this goal is considered to be beyond far-fetched. I would recommend that we use `options` page to act as a patch/holder before we can even think about getting into separate login

2020-11-03 21:54 UTC, MrNickWan commented
Yes, I understand this thought process.

But I have a number of concerns:
1. The time values for each student will most likely be different. The
X-Axis is a continuous axis rather than discrete.
Perhaps you mean that we should group student questions within a certain
time range?

2. That's fine.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

On Tue, Nov 3, 2020 at 1:04 PM Jason C <notifications@github.com> wrote:

> *@JKChenFZ* requested changes on this pull request.
>
> I'm confused as to how we would display active feedback as a bar graph. A
> bar graph implies we have distinct categories for each individual bar. But
> students are submitting their own individual questions. We would have as
> many bars as student questions. Or would each bar represent a separate
> video?
>
> The way I envision active feedback is that, the graph is filled with
> individual bar where the x-axis is the discrete timestamp of a video and
> the y-axis is the occurrences of questions. Even though each student ask
> his or her own questions, we still want a way to link similar questions
> together. The way I would like to define similarity is through the
> corresponding timestamp. If A and B both ask a question at time 100 in
> the same video, the active feedback graph should have a bar of height 2
> at timestamp 100. By clicking on that bar in the graph, a modal should
> pop up illustrating the actual textual content.
>
> A asked: ********
> B asked: ***************
>
> ------------------------------
>
> In extension/.eslintrc.json
> <https://github.com/JKChenFZ/Minerva/pull/57#discussion_r516848147>:
>
> > @@ -39,6 +39,7 @@
>          "YT": false,
>          "Snackbar": false,
>          "tf": false,
> -        "blazeface": false
> +        "blazeface": false,
> +        "Chart": false
>
> If you install it correctly, this should not be here
> ------------------------------
>
> In extension/dist/manifest.json
> <https://github.com/JKChenFZ/Minerva/pull/57#discussion_r516848510>:
>
> > @@ -26,7 +26,7 @@
>      "scripts": ["js/Background.js"],
>      "persistent": false
>    },
> -  "content_security_policy": "script-src 'self' 'sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z' 'sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV' 'sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0='; object-src 'self'" ,
> +  "content_security_policy": "script-src 'self' 'sha256-t9UJPrESBeG2ojKTIcFLPGF7nHi2vEc7f5A2KpH/UBU=' 'sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z' 'sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV' 'sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=' 'sha512-qTXRIMyZIFb8iQcfjXWCO8+M5Tbc38Qi5WzdPOYZHIlZpzBHG3L3by84BBBOiRGiEb7KKtAOAs5qYdUiZiQNNQ=='; object-src 'self'" ,
>
> Same as above. Keep the original content under content_security_policy
> untouched should be the route going foward
> ------------------------------
>
> In extension/webpack.config.js
> <https://github.com/JKChenFZ/Minerva/pull/57#discussion_r516849769>:
>
> > @@ -7,7 +7,8 @@ module.exports = {
>          GoogleClassroomContentScript: "./src/content_scripts/google_classroom/GoogleClassroom.js",
>          MinervaMenu: "./src/popups/MinervaMenu.js",
>          StudentRegistration: "./src/standalone_pages/StudentRegistration.js",
> -        StudyModeLocker: "./src/content_scripts/youtube/StudyModeLocker.js"
> +        InstructorDashboard: "./src/standalone_pages/InstructorDashboard.js",
>
> This is fine, but please sort them with respect to alphabetical order
> ------------------------------
>
> In extension/src/popups/MinervaMenu.html
> <https://github.com/JKChenFZ/Minerva/pull/57#discussion_r516855080>:
>
> > @@ -29,6 +29,9 @@
>                <a class="nav-link" id="store-tab" data-toggle="tab" href="#nav-store" role="tab" aria-controls="store"
>                  aria-selected="false">Store</a>
>              </li>
> +            <li class="nav-item">
>
> My first point was really just about hiding the button. I am ok with a
> temporary measure which exposes the button for demonstration purpose.
>
> As with the second approach, ideally, we should separate and containerize
> the context with respect to students and teachers. However, at the current
> rate of implementation, this goal is considered to be beyond far-fetched. I
> would recommend that we use options page to act as a patch/holder before
> we can even think about getting into separate login
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/JKChenFZ/Minerva/pull/57#pullrequestreview-522738706>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFLLD3L3P4NSFETUGSRCZFLSOBAZDANCNFSM4TG2EBEA>
> .
>

2020-11-04 02:07 UTC, JKChenFZ commented
> 1. The time values for each student will most likely be different. The
X-Axis is a continuous axis rather than discrete.
Perhaps you mean that we should group student questions within a certain
time range?

Grouping student questions within a certain time range is a big plus tho most likely out of the scope of this project. You can safely treat all values on the x-axis as discrete. All timestamps are taken and stored as integers. For a video of 350 seconds, there are 351 total possible x values (including 0).

2020-11-06 03:10 UTC, JKChenFZ requested changes
You have saved this branch. Very close very close

2020-11-06 03:10 UTC, Jason-KChen commented on extension/src/standalone_pages/InstructorDashboard.html
> +    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha256-t9UJPrESBeG2ojKTIcFLPGF7nHi2vEc7f5A2KpH/UBU=" crossorigin="anonymous"></script>
remove

2020-11-06 03:10 UTC, Jason-KChen commented on extension/dist/manifest.json
> +  "content_security_policy": "script-src 'self' 'sha256-t9UJPrESBeG2ojKTIcFLPGF7nHi2vEc7f5A2KpH/UBU=' 'sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z' 'sha384-B4gt1jrGC7Jh4Ag
remove the addition

2020-11-06 03:10 UTC, Jason-KChen commented on extension/src/standalone_pages/InstructorDashboard.html
> +    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js" integrity="sha512-qTXRIMyZIFb8iQcfjXWCO8+M5Tbc38Qi5WzdPOYZHIlZpzBHG3L3by84BBBOiRGiEb7KKtAOAs5qYdUiZiQNNQ==" cro
nit: move to npm

2020-11-06 03:10 UTC, Jason-KChen commented on extension/src/standalone_pages/InstructorDashboard.js
> +        console.log(response);
nit: use console.err instead here. Do you not need to specify the extension by "ID" here?

2020-11-06 03:10 UTC, JKChenFZ commented on extension/src/standalone_pages/InstructorDashboardRenderVideoInfo.js
> +        videoButton.innerHTML = `${video.video_title}`;
nit: I think `innerText` is better here. Up to you, `HTML` seems to be an overkill for just setting the title

2020-11-06 03:10 UTC, JKChenFZ commented on extension/webpack.config.js
> +        StudyModeLocker: "./src/content_scripts/youtube/StudyModeLocker.js",
now we can remove the comma

2020-11-08 18:29 UTC, JKChenFZ approved these changes

2020-11-08 18:30 UTC, merged